### PR TITLE
Security attempt2 231 lo

### PR DESCRIPTION
**Pull request by leormsbee**

### CODE REVIEW

**Comment by ashabed** [comment]
@leormsbee FYI you shouldn't commit the website backup file. The idea is to save the backup file for yourself temporarily, in case the update goes bad. Database dumps can be huge or contain private information so it's best not to commit them in the codebase.

**Comment by ashabed** [comment]
@leormsbee this is actually a good opportunity to use some of those 'advanced git' techniques we learned. You want to delete the commit with the database from this branch. Because this branch hasn't been merged into develop, it's OK to rewrite history on this branch.

**Comment by leormsbee** [comment]
@ashabed I'll fix this sometime this weekend and resubmit.  The task instructions said to commit the backup files (or at least that's how I read it): **Backup the files**
Commit your website's files as-is to ensure you can revert to them.  What should I have done instead? Just saved the file?

**Comment by ashabed** [comment]
Thanks for pointing out, I see that it wasn't worded clearly. What was meant by "Commit the website's files.." was the files required to run the website (what we normally commit.)

As for the backup, yes, you should have just saved the file.

**Pull request closed without merging**
